# Generated by Django 5.2.16 on 2026-08-12 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registry_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('common_name', models.CharField(blank=True, max_length=255)),
                ('strength', models.TextField(blank=True)),
                ('pharmaceutical_form', models.CharField(blank=True, max_length=255)),
                ('marketing_holder', models.CharField(blank=True, max_length=255)),
                ('kind', models.CharField(max_length=32)),
                ('permit_number', models.CharField(blank=True, max_length=64)),
                ('leaflet_url', models.URLField(blank=True, max_length=500)),
                ('characteristics_url', models.URLField(blank=True, max_length=500)),
                ('last_seen_as_of', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Substance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_key', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSubstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, max_length=64)),
                ('unit', models.CharField(blank=True, max_length=64)),
                ('preparation_amount', models.CharField(blank=True, max_length=64)),
                ('preparation_unit', models.CharField(blank=True, max_length=64)),
                ('amount_description', models.TextField(blank=True)),
                ('source_field', models.CharField(choices=[('substance_row', 'Explicit substance row'), ('common_name', 'Product common name (inferred)')], max_length=32)),
                ('source_order', models.PositiveSmallIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substance_links', to='registry.product')),
                ('substance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_links', to='registry.substance')),
            ],
            options={
                'ordering': ['source_order'],
            },
        ),
    ]
