# Generated by Django 5.2.16 on 2026-08-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=16)),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled')], max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('source_as_of', models.DateField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('products_loaded', models.PositiveIntegerField(blank=True, null=True)),
                ('products_created', models.PositiveIntegerField(blank=True, null=True)),
                ('products_inactive', models.PositiveIntegerField(blank=True, null=True)),
                ('substances_created', models.PositiveIntegerField(blank=True, null=True)),
                ('links_created', models.PositiveIntegerField(blank=True, null=True)),
                ('products_without_links', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
